version: "3.8" # Specify the Docker Compose version

services:
  db:
    image: postgres:15-alpine
    container_name: elysia
    environment:
      POSTGRES_PASSWORD: elysia
      POSTGRES_DB: elysia
    volumes:
      - postgres_data:/var/lib/postgresql/data # Mount a named volume
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8090:80
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin: